language: python
python:
- 3.7
env:
-SERVER_IP_ADDRESS=13.239.57.170

before_install:
- openssl aes-256-cbc -K $encrypted_dbabf1ba6eef_key -iv $encrypted_dbabf1ba6eef_iv
  -in deploy_key.enc -out ./deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key
- ssh -i ./deploy_key ec2-user@$SERVER_IP_ADDRESS pwd
